<a href="https://colab.research.google.com/github/Maruf0275/Machine-Learning-CIT/blob/main/Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import seaborn as sns
import pandas as pd
import numpy as np

df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
df["age"] = df["age"].fillna(df["age"].median())

In [ ]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
df["embarked"] = df["embarked"].fillna(df["embarked"].mode()[0])

In [ ]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
df["embark_town"] = df["embark_town"].fillna(df["embark_town"].mode()[0])

In [ ]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
deck           688
embark_town      0
alive            0
alone            0
dtype: int64

In [ ]:
df = df.drop("deck", axis=1)

In [ ]:
df.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

In [ ]:
# Replace Encoding
df["sex"] = df["sex"].replace({
    "male": 0,
    "female": 1
})

/tmp/ipykernel_2923/348356490.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["sex"] = df["sex"].replace({

In [ ]:
df["sex"].head()

0    0
1    1
2    1
3    1
4    0
Name: sex, dtype: int64

In [ ]:
df["embarked"].head()

0    S
1    C
2    S
3    S
4    S
Name: embarked, dtype: object

In [ ]:
# Replace Encoding
df["embarked"] = df["embarked"].replace({
    "S": 0,
    "C": 1,
    "Q": 2
})

In [ ]:
df["embarked"].head()

0    0
1    1
2    0
3    0
4    0
Name: embarked, dtype: int64

In [ ]:
# Replace Encoding
df["alive"] = df["alive"].replace({
    "no": 0,
    "yes": 1
})

In [ ]:
df["alive"].head()

0    0
1    1
2    1
3    1
4    0
Name: alive, dtype: int64

In [ ]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,0,22.0,1,0,7.2500,0,Third,man,True,Southampton,0,False
1,1,1,1,38.0,1,0,71.2833,1,First,woman,False,Cherbourg,1,False
2,1,3,1,26.0,0,0,7.9250,0,Third,woman,False,Southampton,1,True
3,1,1,1,35.0,1,0,53.1000,0,First,woman,False,Southampton,1,False
4,0,3,0,35.0,0,0,8.0500,0,Third,man,True,Southampton,0,True

In [ ]:
df['adult_male'] = df['adult_male'].replace({
    True: 1,
    False: 0
})

/tmp/ipykernel_2923/1780192130.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['adult_male'] = df['adult_male'].replace({

In [ ]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,0,22.0,1,0,7.2500,0,Third,man,1,Southampton,0,False
1,1,1,1,38.0,1,0,71.2833,1,First,woman,0,Cherbourg,1,False
2,1,3,1,26.0,0,0,7.9250,0,Third,woman,0,Southampton,1,True
3,1,1,1,35.0,1,0,53.1000,0,First,woman,0,Southampton,1,False
4,0,3,0,35.0,0,0,8.0500,0,Third,man,1,Southampton,0,True

In [ ]:
df['embark_town'].value_counts()

embark_town
Southampton    646
Cherbourg      168
Queenstown      77
Name: count, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [ ]:
le.fit(df['embark_town'])

LabelEncoder()

In [ ]:
df['embark_town'] = le.fit_transform(df['embark_town'])
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,0,22.0,1,0,7.2500,0,Third,man,1,2,0,False
1,1,1,1,38.0,1,0,71.2833,1,First,woman,0,0,1,False
2,1,3,1,26.0,0,0,7.9250,0,Third,woman,0,2,1,True
3,1,1,1,35.0,1,0,53.1000,0,First,woman,0,2,1,False
4,0,3,0,35.0,0,0,8.0500,0,Third,man,1,2,0,True

In [ ]:
df['class'].value_counts()

class
Third     491
First     216
Second    184
Name: count, dtype: int64

In [ ]:
df['class'] = le.fit_transform(df['class'])
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,0,22.0,1,0,7.2500,0,2,man,1,2,0,False
1,1,1,1,38.0,1,0,71.2833,1,0,woman,0,0,1,False
2,1,3,1,26.0,0,0,7.9250,0,2,woman,0,2,1,True
3,1,1,1,35.0,1,0,53.1000,0,0,woman,0,2,1,False
4,0,3,0,35.0,0,0,8.0500,0,2,man,1,2,0,True

In [ ]:
df.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
886,0,2,0,27.0,0,0,13.00,0,1,man,1,2,0,True
887,1,1,1,19.0,0,0,30.00,0,0,woman,0,2,1,True
888,0,3,1,28.0,1,2,23.45,0,2,woman,0,2,0,False
889,1,1,0,26.0,0,0,30.00,1,0,man,1,0,1,True
890,0,3,0,32.0,0,0,7.75,2,2,man,1,1,0,True

In [ ]:
df['who'].value_counts()

who
man      537
woman    271
child     83
Name: count, dtype: int64

In [ ]:
df['who'] = le.fit_transform(df['who'])
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,0,22.0,1,0,7.2500,0,2,1,1,2,0,False
1,1,1,1,38.0,1,0,71.2833,1,0,2,0,0,1,False
2,1,3,1,26.0,0,0,7.9250,0,2,2,0,2,1,True
3,1,1,1,35.0,1,0,53.1000,0,0,2,0,2,1,False
4,0,3,0,35.0,0,0,8.0500,0,2,1,1,2,0,True

In [ ]:
df.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64