<a href="https://colab.research.google.com/github/Maruf0275/Machine-Learning-CIT/blob/main/Python-Libraries/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = [1,2,3,4,5]
data

[1, 2, 3, 4, 5]

In [3]:
print(type(data))

<class 'list'>

In [4]:
df = pd.Series(data)
df

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
print(type(df))

<class 'pandas.core.series.Series'>

In [6]:
df.info

<bound method Series.info of 0    1
1    2
2    3
3    4
4    5
dtype: int64>

In [7]:
df.info()

<class 'pandas.core.series.Series'>
RangeIndex: 5 entries, 0 to 4
Series name: None
Non-Null Count  Dtype
--------------  -----
5 non-null      int64
dtypes: int64(1)
memory usage: 172.0 bytes

In [8]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, 50 ,40, 45],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']
}
df = pd.DataFrame(data)
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   50      Chicago
3    David   40      Houston
4      Eva   45      Phoenix

In [9]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   City    5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

In [11]:
new = [['sajib', 'rajib', 'sydul'], [1, 2, 3], ['a', 'b', 'c']]
df = pd.DataFrame(new, columns=['col1','col2','col3'])
df

    col1   col2   col3
0  sajib  rajib  sydul
1      1      2      3
2      a      b      c

In [12]:
df['col1']

0    sajib
1        1
2        a
Name: col1, dtype: object

In [13]:
data_new = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, 50 ,40, 45],
    'Selary': [50000, 60000, 70000, 80000, 90000]
}
df = pd.DataFrame(data_new)
df

      Name  Age  Selary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   50   70000
3    David   40   80000
4      Eva   45   90000

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   Selary  5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

In [15]:
df.dtypes

Name      object
Age        int64
Selary     int64
dtype: object

In [16]:
df['Age'] = df['Age'].astype('float64')
df.dtypes

Name       object
Age       float64
Selary      int64
dtype: object

In [17]:
df

      Name   Age  Selary
0    Alice  25.0   50000
1      Bob  30.0   60000
2  Charlie  50.0   70000
3    David  40.0   80000
4      Eva  45.0   90000

In [18]:
df['Selary'] = df['Selary'].astype('int32')
df.dtypes

Name       object
Age       float64
Selary      int32
dtype: object

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      float64
 2   Selary  5 non-null      int32
dtypes: float64(1), int32(1), object(1)
memory usage: 232.0+ bytes

In [20]:
df

      Name   Age  Selary
0    Alice  25.0   50000
1      Bob  30.0   60000
2  Charlie  50.0   70000
3    David  40.0   80000
4      Eva  45.0   90000

In [21]:
df['Name']

0      Alice
1        Bob
2    Charlie
3      David
4        Eva
Name: Name, dtype: object

In [22]:
df[['Age','Selary']]

    Age  Selary
0  25.0   50000
1  30.0   60000
2  50.0   70000
3  40.0   80000
4  45.0   90000

In [23]:
df['Age'] == 50.0

0    False
1    False
2     True
3    False
4    False
Name: Age, dtype: bool

In [24]:
df[df['Age'] == 50.0]

      Name   Age  Selary
2  Charlie  50.0   70000

In [25]:
data = np.random.rand(8,4)

for i in range(data.shape[1]):
  nan_val = np.random.choice(6,3,replace = False)
  data[nan_val, i] = np.nan


df  = pd.DataFrame(data, columns = ['A','B','C','D'])
df

          A         B         C         D
0       NaN       NaN       NaN       NaN
1       NaN       NaN  0.905152       NaN
2       NaN  0.388732       NaN       NaN
3  0.487139  0.684665  0.710062  0.514578
4  0.224813  0.443500  0.235632  0.875518
5  0.655139       NaN       NaN  0.661986
6  0.733639  0.089863  0.255683  0.977526
7  0.908693  0.688444  0.395671  0.657784

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      float64
 1   B       5 non-null      float64
 2   C       5 non-null      float64
 3   D       5 non-null      float64
dtypes: float64(4)
memory usage: 388.0 bytes

In [27]:
df.isnull()

       A      B      C      D
0   True   True   True   True
1   True   True  False   True
2   True  False   True   True
3  False  False  False  False
4  False  False  False  False
5  False   True   True  False
6  False  False  False  False
7  False  False  False  False

In [28]:
df.isnull().sum()

A    3
B    3
C    3
D    3
dtype: int64

In [29]:
df.describe()

              A         B         C         D
count  5.000000  5.000000  5.000000  5.000000
mean   0.601885  0.459041  0.500440  0.737478
std    0.259652  0.247492  0.295271  0.186019
min    0.224813  0.089863  0.235632  0.514578
25%    0.487139  0.388732  0.255683  0.657784
50%    0.655139  0.443500  0.395671  0.661986
75%    0.733639  0.684665  0.710062  0.875518
max    0.908693  0.688444  0.905152  0.977526

In [30]:
data_new = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, 50 ,40, 45],
    'Selary': [50000, 60000, 70000, 80000, 90000]
}
df = pd.DataFrame(data_new)
df

      Name  Age  Selary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   50   70000
3    David   40   80000
4      Eva   45   90000

In [31]:
df.shape

(5, 3)

In [32]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [33]:
df.columns

Index(['Name', 'Age', 'Selary'], dtype='object')

In [34]:
df.head(2)

    Name  Age  Selary
0  Alice   25   50000
1    Bob   30   60000

In [35]:
df.tail(2)

    Name  Age  Selary
3  David   40   80000
4    Eva   45   90000

In [36]:
df.sample(2)

    Name  Age  Selary
4    Eva   45   90000
3  David   40   80000

In [37]:
df

      Name  Age  Selary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   50   70000
3    David   40   80000
4      Eva   45   90000

In [38]:
df = df.rename(columns={'Selary':'Income'})
df

      Name  Age  Income
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   50   70000
3    David   40   80000
4      Eva   45   90000

In [39]:
df.min()

Name      Alice
Age          25
Income    50000
dtype: object

In [40]:
df.max()

Name        Eva
Age          50
Income    90000
dtype: object

In [41]:
df.shape[0]

5

In [43]:
data = np.random.rand(8,4)

for i in range(data.shape[1]):
  nan_val = np.random.choice(6,3,replace = False)
  data[nan_val, i] = np.nan


df  = pd.DataFrame(data, columns = ['A','B','C','D'])
df

          A         B         C         D
0  0.806290  0.798408       NaN  0.431417
1       NaN  0.903941       NaN       NaN
2       NaN       NaN  0.327668  0.126405
3  0.156761       NaN  0.377410       NaN
4  0.990195       NaN  0.941833  0.209460
5       NaN  0.556497       NaN       NaN
6  0.107336  0.149160  0.159470  0.151292
7  0.279426  0.918426  0.401025  0.196506

In [44]:
df1 = df.copy()
df2 = df.copy()
df3 = df.copy()
df4 = df.copy()

In [45]:
df.tail(2)

          A         B         C         D
6  0.107336  0.149160  0.159470  0.151292
7  0.279426  0.918426  0.401025  0.196506

In [46]:
df[3:6]

          A         B         C        D
3  0.156761       NaN  0.377410      NaN
4  0.990195       NaN  0.941833  0.20946
5       NaN  0.556497       NaN      NaN

In [47]:
df

          A         B         C         D
0  0.806290  0.798408       NaN  0.431417
1       NaN  0.903941       NaN       NaN
2       NaN       NaN  0.327668  0.126405
3  0.156761       NaN  0.377410       NaN
4  0.990195       NaN  0.941833  0.209460
5       NaN  0.556497       NaN       NaN
6  0.107336  0.149160  0.159470  0.151292
7  0.279426  0.918426  0.401025  0.196506

In [48]:
df = df.fillna(2)
df

          A         B         C         D
0  0.806290  0.798408  2.000000  0.431417
1  2.000000  0.903941  2.000000  2.000000
2  2.000000  2.000000  0.327668  0.126405
3  0.156761  2.000000  0.377410  2.000000
4  0.990195  2.000000  0.941833  0.209460
5  2.000000  0.556497  2.000000  2.000000
6  0.107336  0.149160  0.159470  0.151292
7  0.279426  0.918426  0.401025  0.196506

In [49]:
df1

          A         B         C         D
0  0.806290  0.798408       NaN  0.431417
1       NaN  0.903941       NaN       NaN
2       NaN       NaN  0.327668  0.126405
3  0.156761       NaN  0.377410       NaN
4  0.990195       NaN  0.941833  0.209460
5       NaN  0.556497       NaN       NaN
6  0.107336  0.149160  0.159470  0.151292
7  0.279426  0.918426  0.401025  0.196506

In [50]:
df1['B'] = df1['B'].fillna(1)

In [51]:
df1

          A         B         C         D
0  0.806290  0.798408       NaN  0.431417
1       NaN  0.903941       NaN       NaN
2       NaN  1.000000  0.327668  0.126405
3  0.156761  1.000000  0.377410       NaN
4  0.990195  1.000000  0.941833  0.209460
5       NaN  0.556497       NaN       NaN
6  0.107336  0.149160  0.159470  0.151292
7  0.279426  0.918426  0.401025  0.196506

In [52]:
df1.fillna({'A':2,'C':3,'D':4},inplace=True)
df1

          A         B         C         D
0  0.806290  0.798408  3.000000  0.431417
1  2.000000  0.903941  3.000000  4.000000
2  2.000000  1.000000  0.327668  0.126405
3  0.156761  1.000000  0.377410  4.000000
4  0.990195  1.000000  0.941833  0.209460
5  2.000000  0.556497  3.000000  4.000000
6  0.107336  0.149160  0.159470  0.151292
7  0.279426  0.918426  0.401025  0.196506

In [53]:
df2

          A         B         C         D
0  0.806290  0.798408       NaN  0.431417
1       NaN  0.903941       NaN       NaN
2       NaN       NaN  0.327668  0.126405
3  0.156761       NaN  0.377410       NaN
4  0.990195       NaN  0.941833  0.209460
5       NaN  0.556497       NaN       NaN
6  0.107336  0.149160  0.159470  0.151292
7  0.279426  0.918426  0.401025  0.196506

In [54]:
df2['A'].mean()

np.float64(0.4680014683936148)

In [55]:
df2['A'].fillna(df2['A'].mean(),inplace=True)
df2

/tmp/ipykernel_3451/1787873680.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['A'].fillna(df2['A'].mean(),inplace=True)

          A         B         C         D
0  0.806290  0.798408       NaN  0.431417
1  0.468001  0.903941       NaN       NaN
2  0.468001       NaN  0.327668  0.126405
3  0.156761       NaN  0.377410       NaN
4  0.990195       NaN  0.941833  0.209460
5  0.468001  0.556497       NaN       NaN
6  0.107336  0.149160  0.159470  0.151292
7  0.279426  0.918426  0.401025  0.196506

In [57]:
df2.dropna(axis = 0)

          A         B         C         D
6  0.107336  0.149160  0.159470  0.151292
7  0.279426  0.918426  0.401025  0.196506

In [58]:
df3

          A         B         C         D
0  0.806290  0.798408       NaN  0.431417
1       NaN  0.903941       NaN       NaN
2       NaN       NaN  0.327668  0.126405
3  0.156761       NaN  0.377410       NaN
4  0.990195       NaN  0.941833  0.209460
5       NaN  0.556497       NaN       NaN
6  0.107336  0.149160  0.159470  0.151292
7  0.279426  0.918426  0.401025  0.196506

In [60]:
df3.drop(['D'],inplace=True, axis =1)

In [61]:
df3

          A         B         C
0  0.806290  0.798408       NaN
1       NaN  0.903941       NaN
2       NaN       NaN  0.327668
3  0.156761       NaN  0.377410
4  0.990195       NaN  0.941833
5       NaN  0.556497       NaN
6  0.107336  0.149160  0.159470
7  0.279426  0.918426  0.401025

In [65]:
import requests
from io import StringIO

In [66]:
data_path = 'https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv'

In [64]:
response = requests.get(data_path)
response

In [68]:
data = StringIO(response.text)

In [69]:
data = pd.read_csv(data)
data

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [70]:
data.head(5)

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [73]:
data.tail(2)

     sepal.length  sepal.width  petal.length  petal.width    variety
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

In [74]:
import requests
from io import StringIO

In [75]:
data_link = 'https://raw.githubusercontent.com/azminewasi/Lionel-Messi-Club-Goals/refs/heads/main/data.csv'

In [76]:
response = requests.get(data_link)
response

In [77]:
data = StringIO(response.text)

In [78]:
data = pd.read_csv(data)
data

,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,Minute,At_score,Type,Goal_assist
0,04/05,LaLiga,34,05-01/05,H,FC Barcelona,Albacete Balompie,2:00,CF,90+1,2:00,Left-footed shot,Ronaldinho Gaacho
1,05/06,UEFA Champions League,Group Stage,11-02/05,H,FC Barcelona,Panathinaikos Athens,5:00,RW,34,3:00,Left-footed shot,NaN
2,05/06,LaLiga,13,11/27/05,H,FC Barcelona,Racing Santander,4:01,RW,51,2:00,Left-footed shot,Samuel Etoo
3,05/06,LaLiga,19,1/15/06,H,FC Barcelona,Athletic Bilbao,2:01,RW,50,2:01,Left-footed shot,Mark van Bommel
4,05/06,LaLiga,20,1/22/06,H,FC Barcelona,Deportivo Alaves,2:00,CF,82,2:00,Left-footed shot,Ronaldinho Gaacho
...,...,...,...,...,...,...,...,...,...,...,...,...,...
699,22/23,Ligue 1,21,2/1/23,A,Paris Saint-Germain,Montpellier HSC,1:3,SS,72,0:2,Left-footed shot,Fabián Ruiz
700,22/23,Ligue 1,22,2/4/23,H,Paris Saint-Germain,FC Toulouse,2:1,SS,58,2:1,Left-footed shot,Achraf Hakimi
701,22/23,Ligue 1,24,2/19/23,H,Paris Saint-Germain,LOSC Lille,4:3,CF,90+5,4:3,Direct free kick,\t
702,22/23,Ligue 1,25,2/26/23,A,Paris Saint-Germain,Olympique Marseille,0:3,CF,29,0:2,Right-footed shot,Kylian Mbappé
703,22/23,Ligue 1,26,3/4/23,H,Paris Saint-Germain,FC Nantes,4:2,CF,12,1:0,Left-footed shot,NaN

In [80]:
data[200:206]

,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,Minute,At_score,Type,Goal_assist
200,11-Dec,UEFA Champions League,Group Stage,11-01/11,A,FC Barcelona,FC Viktoria Plzen,0:04,CF,45+2,0:02,Left-footed shot,Adriano
201,11-Dec,UEFA Champions League,Group Stage,11-01/11,A,FC Barcelona,FC Viktoria Plzen,0:04,CF,90+2,0:04,Left-footed shot,Gerard Pique
202,11-Dec,LaLiga,12,11/06/11,A,FC Barcelona,Athletic Bilbao,2:02,CF,90,2:02,Left-footed shot,NaN
203,11-Dec,LaLiga,13,11/19/11,H,FC Barcelona,Real Zaragoza,4:00,CF,43,2:00,Right-footed shot,Cesc Fabregas
204,11-Dec,UEFA Champions League,Group Stage,11/23/11,A,FC Barcelona,AC Milan,2:03,SS,31,1:02,Penalty,NaN
205,11-Dec,LaLiga,17,11/29/11,H,FC Barcelona,Rayo Vallecano,4:00,CF,49,4:00,Left-footed shot,Dani Alves