<a href="https://colab.research.google.com/github/Maruf0275/Machine-Learning-CIT/blob/main/Python-Libraries/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = [1,2,3,4,5]
data

[1, 2, 3, 4, 5]

In [3]:
print(type(data))

<class 'list'>

In [4]:
df = pd.Series(data)
df

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
print(type(df))

<class 'pandas.core.series.Series'>

In [6]:
df.info

<bound method Series.info of 0    1
1    2
2    3
3    4
4    5
dtype: int64>

In [7]:
df.info()

<class 'pandas.core.series.Series'>
RangeIndex: 5 entries, 0 to 4
Series name: None
Non-Null Count  Dtype
--------------  -----
5 non-null      int64
dtypes: int64(1)
memory usage: 172.0 bytes

In [9]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, 50 ,40, 45],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']
}
df = pd.DataFrame(data)
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   50      Chicago
3    David   40      Houston
4      Eva   45      Phoenix

In [10]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   City    5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

In [12]:
new = [['sajib', 'rajib', 'sydul'], [1, 2, 3], ['a', 'b', 'c']]
df = pd.DataFrame(new, columns=['col1','col2','col3'])
df

    col1   col2   col3
0  sajib  rajib  sydul
1      1      2      3
2      a      b      c

In [13]:
df['col1']

0    sajib
1        1
2        a
Name: col1, dtype: object

In [14]:
data_new = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, 50 ,40, 45],
    'Selary': [50000, 60000, 70000, 80000, 90000]
}
df = pd.DataFrame(data_new)
df

      Name  Age  Selary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   50   70000
3    David   40   80000
4      Eva   45   90000

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   Selary  5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

In [16]:
df.dtypes

Name      object
Age        int64
Selary     int64
dtype: object

In [18]:
df['Age'] = df['Age'].astype('float64')
df.dtypes

Name       object
Age       float64
Selary      int64
dtype: object

In [19]:
df

      Name   Age  Selary
0    Alice  25.0   50000
1      Bob  30.0   60000
2  Charlie  50.0   70000
3    David  40.0   80000
4      Eva  45.0   90000

In [20]:
df['Selary'] = df['Selary'].astype('int32')
df.dtypes

Name       object
Age       float64
Selary      int32
dtype: object

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      float64
 2   Selary  5 non-null      int32
dtypes: float64(1), int32(1), object(1)
memory usage: 232.0+ bytes

In [22]:
df

      Name   Age  Selary
0    Alice  25.0   50000
1      Bob  30.0   60000
2  Charlie  50.0   70000
3    David  40.0   80000
4      Eva  45.0   90000

In [23]:
df['Name']

0      Alice
1        Bob
2    Charlie
3      David
4        Eva
Name: Name, dtype: object

In [24]:
df[['Age','Selary']]

    Age  Selary
0  25.0   50000
1  30.0   60000
2  50.0   70000
3  40.0   80000
4  45.0   90000

In [25]:
df['Age'] == 50.0

0    False
1    False
2     True
3    False
4    False
Name: Age, dtype: bool

In [26]:
df[df['Age'] == 50.0]

      Name   Age  Selary
2  Charlie  50.0   70000

In [27]:
data = np.random.rand(8,4)

for i in range(data.shape[1]):
  nan_val = np.random.choice(6,3,replace = False)
  data[nan_val, i] = np.nan


df  = pd.DataFrame(data, columns = ['A','B','C','D'])
df

          A         B         C         D
0       NaN       NaN       NaN       NaN
1  0.357954  0.738182       NaN       NaN
2       NaN       NaN       NaN  0.522149
3       NaN  0.040744  0.538262  0.726667
4  0.083974       NaN  0.645666       NaN
5  0.901012  0.933976  0.483645  0.698832
6  0.248429  0.959537  0.804298  0.665389
7  0.091520  0.883863  0.209991  0.301709

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      float64
 1   B       5 non-null      float64
 2   C       5 non-null      float64
 3   D       5 non-null      float64
dtypes: float64(4)
memory usage: 388.0 bytes

In [29]:
df.isnull()

       A      B      C      D
0   True   True   True   True
1  False  False   True   True
2   True   True   True  False
3   True  False  False  False
4  False   True  False   True
5  False  False  False  False
6  False  False  False  False
7  False  False  False  False

In [30]:
df.isnull().sum()

A    3
B    3
C    3
D    3
dtype: int64

In [31]:
df.describe()

              A         B         C         D
count  5.000000  5.000000  5.000000  5.000000
mean   0.336578  0.711261  0.536373  0.582949
std    0.335662  0.384497  0.219680  0.175836
min    0.083974  0.040744  0.209991  0.301709
25%    0.091520  0.738182  0.483645  0.522149
50%    0.248429  0.883863  0.538262  0.665389
75%    0.357954  0.933976  0.645666  0.698832
max    0.901012  0.959537  0.804298  0.726667